# Generated by Django 6.0.5 on 2026-05-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'is_primary')},
        ),
    ]
