# Generated by Django 6.0.5 on 2026-05-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0002_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
