# Generated by Django 6.0.5 on 2026-05-21 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profiles/'),
        ),
        migrations.AddField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
