# Generated by Django 6.0.5 on 2026-05-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_remove_admin_phone_number_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
