# Generated by Django 6.0.5 on 2026-05-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
