# Generated by Django 6.0.5 on 2026-05-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0004_user_created_at_user_updated_at_alter_user_password'),
        ('user', '0003_delete_category'),
        ('wadmin', '0004_product_image_alter_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wadmin.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest.user')),
            ],
            options={
                'db_table': 'tbl_cart',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_key', 'product'), name='unique_session_product')],
            },
        ),
    ]
